[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "hongkong-skymaps"
dynamic = ["version"]
description = "Getting you from A to B via Hong Kong's skys."
readme = "README.md"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
authors = [{name = "Salman Naqvi", email = "salmanaqvi+github@icloud.com"}]
keywords = ['nbdev']
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = []

[project.urls]
Repository = "https://github.com/ForBo7/hongkong-skymaps"
Documentation = "https://ForBo7.github.io/hongkong-skymaps/"

[project.entry-points.nbdev]
hongkong_skymaps = "hongkong_skymaps._modidx:d"

[tool.setuptools.dynamic]
version = {attr = "hongkong_skymaps.__version__"}

[tool.setuptools.packages.find]
include = ["hongkong_skymaps"]

[tool.nbdev]
