# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hongkong-skymaps',
                'doc_host': 'https://ForBo7.github.io',
                'git_url': 'https://github.com/ForBo7/hongkong-skymaps',
                'lib_path': 'hongkong_skymaps'},
  'syms': {'hongkong_skymaps.core': {'hongkong_skymaps.core.foo': ('core.html#foo', 'hongkong_skymaps/core.py')}}}
